### ISSUE TITLE
Typo, and more general question

### ISSUE THREAD

**Issue by eddelbuettel** [clement-lee/crandep#1]
Congrats on getting crandep onto CRAN.  So far I have only looked at the [CRANberries report](http://dirk.eddelbuettel.com/cranberries/2020/05/16#crandep_0.0.1) (though I read it via Feedly and RSS) and not in any detail but I have two suggestions.   

First, you wrote 'scrapping' in the DE, you probably meant 'scraping'.

Second, do you know about `tools::CRAN_package_db()`?  It is what CRAN uses (and lets us use) and likely easier/faster than scraping:

```r
R> db <- tools::CRAN_package_db()
R> length(tools::dependsOnPkgs("Rcpp", recursive=FALSE, installed=db))
[1] 1939
R> length(tools::dependsOnPkgs("Rcpp", recursive=TRUE, installed=db))
[1] 7528
R> 
```

Apologies if I missed something obvious.

**Comment by clement-lee** [comment]
Hi Dirk, thanks for the suggestions. I will make the possible changes in the next version.

**Comment by clement-lee** [comment]
I've added an argument `scrape` which uses `tools::CRAN_package_db()` when FALSE in `get_dep_df()` and `get_dep_all()`. Scraping is slightly faster when only individual packages are concerned, while `tools::CRAN_package_db()` is faster when the whole ecosystem / dependency network is concerned. Both should give the same result anyway.
